GET http://localhost:3000/sections/2?orderby=business_name
Content-Type: application/json

###
GET http://localhost:3000/ratings/4
Content-Type: application/json

###
GET http://localhost:3000
Content-Type: application/json

###
GET http://localhost:3000/sections
Content-Type: application/json

###
GET http://localhost:3000/menus/businesses/1
Content-Type: application/json